feat!: Now works with v6 API
eclipse-tractusx/bpdm-upload-tool pull request #1
Opened 2024-05-27 06:47 UTC by flozf

## Description

Updated the API for the V6 API (mainly additional `state`s)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-24 12:12 UTC, SujitMBRDI commented on CONTRIBUTING.md
> +The project maintains the source code repositories in the following GitHub organization:
@flozf, license file and contributing file need changes.
Could you please adapt the change mentioned here in issue #2

2024-06-24 12:13 UTC, SujitMBRDI commented on NOTICE.md
> +This program and the accompanying materials are made available under the terms
Same changes needed here #2

2024-06-24 12:14 UTC, SujitMBRDI requested changes
Changes need to be adapted for License and docs.
Once that is done, we can create IP issue for this repository.
Please confirm once it is done.

2024-06-24 13:41 UTC, flozf commented
Done

2024-06-25 12:16 UTC, SujitMBRDI commented
> Done

Thanks for adapting changes, But I do have some small recommendations.

2024-06-25 12:19 UTC, SujitMBRDI commented on .vscode/launch.json
> +    //################################################################################
These copyright header inside json file doesn't make sense.
Can you confirm the impact on adding .vscode files to gitignore? as these are IDE specific configurations and should not be present on open source repository.

2024-06-25 12:22 UTC, SujitMBRDI commented on .vscode/settings.json
> +    //################################################################################
Same applies here as well, copyright headers doesn't make sense and please confirm about the impact on removing .vscode directory.

2024-06-25 12:29 UTC, SujitMBRDI commented on CODE_OF_CONDUCT.md
> +**Version 1.2
There is version mismatch in this file.
Kindly read [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#code-of-conduct) 
The Version 2.0 of the Eclipse Foundation Community Code of Conduct was released on Jan 01, 2023.

2024-06-25 13:00 UTC, SujitMBRDI requested changes

2024-06-25 13:00 UTC, SujitMBRDI commented on DEPENDENCIES.dash
> +pypi/pypi/-/requests/2.31.0
Why DEPENDENCIES file with .dash extension here?
Please make sure you have used dash command properly, you can use this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04/#checking-libraries-using-the-eclipse-dash-license-tool) Section for more information.

2024-06-25 13:00 UTC, SujitMBRDI commented on SECURITY.md
> +## Reporting a Vulnerability
Content of file doesn't look correct.
Kindly follow [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file)

2024-06-25 13:02 UTC, SujitMBRDI requested changes
After the requested changes have been added to the PR, it is a good starting point for an initial contribution and the IP-Check.

2024-06-27 09:12 UTC, SujitMBRDI commented
@flozf,
I have created an IP-Check issue at EF: [https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15499](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15499)

2024-07-10 08:26 UTC, SebastianBezold requested changes

2024-07-10 08:26 UTC, SebastianBezold commented on DEPENDENCIES
The  `DEPENDENCIES` file is incomplete. 
Did you generate it with the [Eclipse Dash License Tool](https://github.com/eclipse/dash-licenses)?
The Licenses and EF approvals + IP Lab issue numbers are missing.

In case you need help doing that for Python dependencies, please contact @AngelikaWittek for info

2024-07-15 07:53 UTC, AngelikaWittek commented
@SujitMBRDI can you please inform us  when this PR will be ready to be merged? This repository is planned to be archived before end of July.

2024-07-15 11:12 UTC, SujitMBRDI commented
> @SujitMBRDI can you please inform us when this PR will be ready to be merged? This repository is planned to be archived before end of July.

@AngelikaWittek, I had discussion with business person. This repo is not going to be use as now so we are ready to Archive same. I shall merge the PR and will close open issue.

2024-07-15 11:13 UTC, merged